#! /bin/sh
bspc rule -r "*"
setxkbmap us
sxhkd &

if [ "$(xrandr -q | grep " connected" | awk '{print $1}' | wc -l)" -eq "2" ]; then
	bspc monitor "$(xrandr -q | grep " connected" | awk '{print $1}' | sort | sed -n 1p)" -d 1 2 3 4 5
	bspc monitor "$(xrandr -q | grep " connected" | awk '{print $1}' | sort | sed -n 2p)" -d 6 7 8 9 10
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

#bspc config single_monocle true
#bspc config gapless_monocle true
#bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config normal_border_color "#2f364a"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#eeeeee"

bspc config window_gap 15
bspc config border_width 1
bspc config border_radius 7


#bspc config border_width         4
#bspc config border_radius         12
#bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/Pictures/f94f4f.png
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
betterlockscreen -u ~/Pictures/f94f4f.png
# Start picom (compton)
#startup_lock_file=/tmp/bspwm-startup.lock
#if [ ! -f $startup_lock_file ]; then
#    echo "dummy" > $startup_lock_file
#wal -i Downloads/CmqBn5A.jpg &
redshift &
xrdb -load ~/.Xresources &
picom &
optimus-manager-qt &
nm-applet &
wmname LG3D &
~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#fi
